language: ko

reviews:
  auto_review: true
  review_depth: medium

  path_filters:
    include:
      - "app/**/*.{ts,tsx}"
      - "components/**/*.{ts,tsx}"
      - "lib/**/*.{ts,tsx}"
      - "store/**/*.{ts,tsx}"
    exclude:
      - "node_modules/**"
      - ".next/**"
      - "public/**"
      - "pnpm-lock.yaml"

  focus_areas:
    - performance
    - accessibility
    - type-safety
    - react-best-practices
    - nextjs-best-practices

tone: friendly

tests:
  required: false

security:
  enabled: true
